apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: nodejs-aks-app
  newName: bahajian/nodejs-aks-app
  newTag: latest
