apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: nodejs-1338
  name: nodejs-1338
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-1338
  name: nodejs-1338
  namespace: nodejs-1338
spec:
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: nodejs-1338
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-1338
  name: nodejs-1338
  namespace: nodejs-1338
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-1338
  template:
    metadata:
      labels:
        app: nodejs-1338
    spec:
      containers:
      - image: bahajian/nodejs-1338:v0.0.1
        name: nodejs-aks-app
        ports:
        - containerPort: 1338
          name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
